### ISSUE TITLE
Feature Request - Users - Add users statuses

### ISSUE THREAD

**Issue by patricklindsay** [yamasolutions/integral#22]
Currently there is no way of managing user states. A user can only remove or create another user. Sometimes it's useful to simply deactivate user accounts so that they no longer have access but they are still available in the system.

Would also be good to add some kind of pending status which only changes to active once the user has successfully setup their password and signed in. Gives admin users more visibility when onboarding new users.

**Comment by michael-reyes-93** [comment]
can I take this request?

**Comment by patricklindsay** [comment]
Sure! 👍
