### ISSUE TITLE
Feature request: No way to set the root page in the UI

### ISSUE THREAD

**Issue by phil9690** [yamasolutions/integral#4]
## Description of issue
When creating a new app I had to either edit the demo page and use that as the root page, or manually edit the path of a new page in the DB. Entering the URL of `/` was not allowed when creating a new page. A user should be able to do this, or have a checkbox setting to say this is the root page, so the URL is automatically `/`.

## Current behaviour
No way to set a new page as the root page (nothing I could see in the UI suggests I can do this).

## Expected behaviour
A way for users to easily set the root page, a restriction should be in place to prevent users from trying to create multiple root pages.

**Comment by patricklindsay** [comment]
You can set the homepage in the settings area `Homepage Page ID` as mentioned in [Integral Pages](https://github.com/yamasolutions/integral/blob/master/docs/integral_pages.md#setting-the-homepage) guide.

Don't think its really worth putting anywhere else yet as this is only going to happen very occasionally and should be locked down to admins only.

That being said, could be nice to add something in the future Pages dashboard, i.e. "Current homepage is 'My Awesome Homepage', change it here."
