### ISSUE TITLE
Feature request: overrides generator for assets/views

### ISSUE THREAD

**Issue by phil9690** [yamasolutions/integral#6]
## Description of issue

It would be handy to have multiple generators that will add overrides for frontend assets/views and backend assets/views. Most of the time I will want to override the frontend, so having a command to do this for me would be good.

**Comment by patricklindsay** [comment]
Yep this would definitely be useful. [Devise does this](https://github.com/plataformatec/devise/blob/master/lib/generators/devise/views_generator.rb) for its views.

I can imagine 2 or 4 tasks, broken up between assets and views and potentially also split for backend and frontend.

Current workaround is to clone the Github repo and copy files over.
